apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_USER: YmFja2VuZA==
  REDIS_PASS: OWY5OGI3YzdmMDcxNzE0NTE3ZDlhNWU2N2MxMzViNDFmYTNlOTFmMjBiYWMxMDgxNThiMzNiMDczMzk2ZjZlNQ==
