apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stateful
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        command: ["redis-server", "/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
      volumes:
          - name: redis-config
            configMap:
              name: redis-config
          - name: redis-data
            emptyDir: {}  # Change to persistent storage if needed
