apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stateful
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        command: ["redis-server", "/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_USER
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_USER
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASS
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        - name: acl
          mountPath: /etc/redis/acl  # ✅ Mount the secret in a directory


      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: acl
          secret:
            secretName: redis-acl

  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
